### ISSUE TITLE
not taking Api Key

### ISSUE THREAD

**Issue by sil3nci0** [vc5/Hpool-Miner-Chia-Docker#1]
Hi there, 

I've tried your docker, but i only get :

"请输入Chia矿池ApiKey：
请输入Chia矿池ApiKey：
请输入Chia矿池ApiKey：
请输入Chia矿池ApiKey：
请输入Chia矿池ApiKey："

i've executed as shown in code section (with my config.yaml in opt), tried modifing the  config.yaml downladed with code but not luck.

Example of executiong:
docker run --name Miminer -v /path/to/plots/:/media/ChiaDisk -v /path/to/config:/opt/config.yaml vincent5/hpool-chia-miner >docker.log 2>&1 &

**Comment by vc5** [comment]
You should get your apikey from `hpool.com`,and put it in config.yaml.

**Comment by sil3nci0** [comment]
hi there. 
my apikey is in my config.yaml (the one allocated in /opt/config.yaml). I'm usin hpool from a time now. I'm trying to run miner in a rpi3 (not in my main pc with ubuntu where i'm running miner correctly ) but as there's the 'connection" issue with miner v1.4.0-2 for arm i was giving a try to the docker.

I'm using my working config.yaml. Should i use the one provided with your code just pasting my ApiKey in it?

**Comment by vc5** [comment]
looks like you got the direction of the mapping wrong.

try this , replace `/path/to/your/config.yaml`  
`docker run --name Miminer -v /media/ChiaDisk:/plots -v /path/to/your/config.yaml:/opt/config.yaml vincent5/hpool-chia-miner `

**Comment by sil3nci0** [comment]
Hi...
Thank you so much. It kindda worked.

The config file must define var 'path' as '- /plots'  and '/path/to/your/config.yaml' must be something like '/home/foo/config.yaml'

Working as a miracle in my rpi3.
