### ISSUE TITLE
chia pp need support,can you upgrade it to 1.5.0.2 

### ISSUE THREAD

**Issue by zhugcx** [vc5/Hpool-Miner-Chia-Docker#2]
i need hpool chia miner 1.5.0.2, can you help me

**Comment by vc5** [comment]
try this 
https://github.com/vc5/chia-miner-hpool-pp-docker

**Comment by zhugcx** [comment]
> 
> 
> try this
> https://github.com/vc5/chia-miner-hpool-pp-docker

thank you, it can run
